# pytest.ini
[pytest]
addopts = -q
filterwarnings =
    ignore::DeprecationWarning:numexpr\..*
    ignore::DeprecationWarning:matplotlib\..*
    ignore::DeprecationWarning:setuptools\..*
    ignore:distutils Version classes are deprecated:DeprecationWarning
